export enum EPISODE_FIELDS {
  NO = "no",
  TITLE = "title",
  RATING = "rating",
  STATUS = "status",
  AUTHOR_ID = "authorId",
  PODCAST_ID = "podcastId",
  CREATED_AT = "createdAt",
  PLAY_COUNT = "playCount",
  RATE_COUNT = "rateCount",
  UPDATED_AT = "updatedAt",
  DESCRIPTION = "description",
  PATH_TO_FILE = "pathToFile",
  AUDIENCE_SIZE = "audienceSize",
  PUBLISHED_DATE = "publishedDate",
  PATH_TO_IMG_FILE = "pathToImgFile",
}
