export enum CreateSeriesSteps {
  INPUT_SERIES_DETAILS = "INPUT_SERIES_DETAILS",
  UPLOAD_SERIES_COVER_IMG = "UPLOAD_SERIES_COVER_IMG",
  CONFIRM_DETAILS_AND_CREATION = "CONFIRM_DETAILS_AND_CREATION",
}
