export const FORM_DEFAULT_VALUES = {
  BIO: "",
  NAME: "",
  DATE: "",
  YEAR: "",
  MONTH: "",
  EMAIL: "",
  TITLE: "",
  GENDER: "",
  AVATAR: undefined,
  PASSWORD: "",
  CATEGORY: "",
  DESCRIPTION: "",
  CATEGORIES_OF_INTEREST: [],
};
